### ISSUE TITLE
[Question] - Icon wanted

### ISSUE THREAD

**Issue by abrochet** [taqueci/redmine_share#3]
Hello,

Thank you for the plugin it is great!

I would need help because I tried to search but I failed. Do you know why the icon does not show up with the theme: [https://github.com/Nitrino/flatly_light_redmine](https://github.com/Nitrino/flatly_light_redmine)

Thank you

**Comment by taqueci** [comment]
Hi @abrochet 

I've got no idea to solve by changing the plugin right now.

Could you please modify the theme as:
```diff
--- a/public/themes/flatly_light_redmine/stylesheets/font-awesome.css
+++ b/public/themes/flatly_light_redmine/stylesheets/font-awesome.css
 .icon-del{
   cursor: pointer;
 }
+.icon-share:before {
+  content: "\f1e0";
+}
```

**Comment by abrochet** [comment]
Hello,
Sorry for the late response. I just tried it works! Thank you so much !
Bye
